name: Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Make Gradle executable
        run: chmod +x gradlew

      - name: Restore debug keystore
        run: |
          if [ -f debug.keystore.base64 ] && [ ! -f debug.keystore ]; then
            base64 -d debug.keystore.base64 > debug.keystore
          fi

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Pixel-Recorder-debug
          path: app/build/outputs/apk/debug/*.apk
